---
- name: Build Docker image using docker-compose
  hosts: build1
  
  vars:
    compose_file: "/home/ubuntu/neptune-v3-release/docker-compose.linux.yml"
    service_name: "neptune-api"

  tasks:


    - name: disk usage
      shell: df -h / | awk 'NR==2 {print $5}' | cut -d'%' -f1
      register: disk_usage
      changed_when: false

    - name: Debug disk usage
      debug:
        msg: "Current disk usage is {{ disk_usage.stdout }}%"

    - name: Check disk usage threshold
      fail:
        msg: "Disk usage is {{ disk_usage.stdout }}%, which is above the 90% threshold. Build will not proceed."
      when: disk_usage.stdout|int > 90


    - name: Build Docker image using docker-compose
      command: 
        cmd: "docker compose -f {{ compose_file }} build {{ service_name }}"
        chdir: "{{ project_dir }}"
      register: build_result
      changed_when: build_result.rc == 0

    - name: Debug build output
      debug:
        msg: "{{ build_result.stdout_lines }}"
      when: build_result.stdout is defined
