---
- name: Build Docker image using docker-compose
  hosts: build1
  
  vars:
    compose_file: "/home/ubuntu/neptune-v3-release/docker-compose.linux.yml"
    service_name: "neptune-api"
    disk_limit: 90
  tasks:


    - name: disk usage
      shell: df -h / | awk 'NR==2 {print $5}' | cut -d'%' -f1
      register: disk_usage
      changed_when: false

    - name: Debug disk usage
      debug:
        msg: "Current disk usage is {{ disk_usage.stdout }}%"

    - name: Check disk usage threshold
          fail:
            msg: "Disk usage is {{ disk_usage.stdout }}%, which is above the {{ disk_limit }}% threshold. Build will not proceed."
          when: disk_usage.stdout|int > disk_limit


    - name: Build Docker image using docker-compose
      command: 
        cmd: "docker compose -f {{ compose_file }} build {{ service_name }}"
      register: build_result
      changed_when: build_result.rc == 0

    - name: Debug build output
      debug:
        msg: "{{ build_result.stdout_lines }}"
      when: build_result.stdout is defined

    - name: tag image 
      command: 
        cmd: "docker tag neptune-api 103.110.127.42:5000/neptune-api:{{ neptune_api_tag }}"
      register: tag_image_result

    - name: Debug tag image output
      debug:
        msg: "{{ tag_image_result.stdout_lines }}"


    - name: push image 
      command: 
        cmd: "docker push  103.110.127.42:5000/neptune-api:{{ neptune_api_tag }}"
      register: push_image_result

    - name: Debug push image output
      debug:
        msg: "{{ push_image_result.stdout_lines }}"
