---
- name: Build Docker image using docker-compose
  hosts: build1
  
  vars:
    compose_file: "/home/ubuntu/neptune-v3-release/docker-compose.linux.yml"
    neptune_release_dir: "/home/ubuntu/sand-release/neptune-release/"
    values_file: "{{ neptune_release_dir }}tis/values.yaml"
    image: "neptune-api"
    registry: "103.110.127.42:5000"
    registry_image: "{{ registry }}/{{image}}:{{ neptune_api_tag }}"
    disk_limit: 90
  tasks:


    - name: disk usage
      shell: df -h / | awk 'NR==2 {print $5}' | cut -d'%' -f1
      register: disk_usage
      changed_when: false

    - name: Debug disk usage
      debug:
        msg: "Current disk usage is {{ disk_usage.stdout }}%"

    - name: Check disk usage threshold
      fail:
        msg: "Disk usage is {{ disk_usage.stdout }}%, which is above the {{ disk_limit }}% threshold. Build will not proceed."
      when: disk_usage.stdout|int > disk_limit


    - name: Build Docker image using docker-compose
      command: 
        cmd: "docker compose -f {{ compose_file }} build {{ image }}"
      register: build_result
      changed_when: build_result.rc == 0

    - name: Debug build output
      debug:
        msg: "{{ build_result.stdout_lines }}"
      when: build_result.stdout is defined

    - name: tag image 
      command: 
        cmd: "docker tag {{ image }} {{ registry_image }}"


    - name: push image 
      command: 
        cmd: "docker push  {{ registry_image }}"
      register: push_image_result

    - name: Debug push image output
      debug:
        msg: "{{ push_image_result.stdout_lines }}"


    - name: Update neptuneApi image tag in values.yaml
      command:
        cmd: >-
          sed -i '/^\s*neptuneApi:\s*$/{n;/^\s*image:\s*/s#image:.*#image: {{ registry_image }}#}'
          "{{ values_file }}"
      register: sed_output
      changed_when: sed_output.rc == 0 and "1 changed" in sed_output.stdout
      failed_when: sed_output.rc != 0

    - name: git add file
      command: "git add tis/values.yaml"
      args:
        chdir: "{{ neptune_release_dir }}"
      
    - name: git commit file
      command: "git commit -m 'Neptune Api version {{ neptune_api_tag }}'"
      args:
        chdir: "{{ neptune_release_dir }}"
      register: git_commit_out
    
    - name: git commit debug
      debug:
        msg:  "{{ git_commit_out.stdout_lines }}"

    - name: git push
      command: "git commit -m 'Neptune Api version {{ neptune_api_tag }}'"
      args:
        chdir: "{{ neptune_release_dir }}"
      register: git_push_out

    - name: git push debug
      debug:
        msg:  "{{ git_push_out.stdout_lines }}"
