- name: neptune-api build
  hosts: build1

  vars:
    storage_threshold: 90
    docker_compose_file: "/home/ubuntu/neptune-v3-release/docker-compose.linux.yml"

  tasks:
    - name: Check disk usage
      shell: df -h / | awk 'NR==2 {print $5}' | cut -d'%' -f1
      register: disk_usage
      changed_when: false

    - name: Show disk usage
      debug:
        msg: "Current disk usage is {{ disk_usage.stdout }}%"

    - name: Start Neptune-Api build if disk usage is acceptable
      block:
        - name: Building docker image
          shell: docker compose -f {{ docker_compose_file }} build neptune-api
          when: disk_usage.stdout | int < storage_threshold

      rescue:
        - name: Disk usage too high, failing the task
          fail:
            msg: "Disk usage ({{ disk_usage.stdout }}%) is above {{ storage_threshold }}%, build aborted."
          when: disk_usage.stdout | int >= storage_threshold
