---
- name: Access Semaphore Extracted Environment Variables
  hosts: all
  gather_facts: false

  tasks:
    - name: Print extracted variable from environment
      debug:
        msg: "Neptune Tag: {{ lookup('env', 'neptune_tag') }}"
    - name: checking next
      debug:
        msg: ""Neptune Tag: {{ lookup('env', 'ref') }}""
