# - name: webhook test
#   hosts: build1
#   tasks:
#     - name: debug
#       debug:
#         msg: "neptune_tag: {{ neptune_tag }}"

- name: Check storage usage and manage neptune-api build
  hosts: build1

  vars:
    storage_threshold: 90  # Percentage threshold
    target_dir: "/home/ubuntu/neptune-v3-release"
    docker_compose_file: "docker-compose.linux.yml"

  tasks:
    - name: disk usage
      shell: df -h / | awk 'NR==2 {print $5}' | cut -d'%' -f1
      register: disk_usage
      changed_when: false

    - name: Debug disk usage
      debug:
        msg: "Current disk usage is {{ disk_usage.stdout }}%"

    - name: Start Neptune-Api Build
      block:
        - name: Navigate to neptune directory and build docker compose
          shell: |
            cd {{ target_dir }}
            docker compose -f {{ docker_compose_file }} build neptune-api
          when: disk_usage.stdout | int > storage_threshold

      rescue:
        - name: Fail due to no disk space
          fail:
            msg: "Disk usage ({{ disk_usage.stdout }}%) is below {{ storage_threshold }}%, job failed as per requirements"
          when: disk_usage.stdout | int <= storage_threshold
