---
- name: Access Semaphore Extracted Environment Variables
  hosts: build1
  gather_facts: false

  tasks:
    - name: Print extracted variable from environment
      debug:
        msg: "Neptune Tag: {{ lookup('env', 'neptune-tag') }}"
