---
- name: Build Docker image using docker-compose
  hosts: build1  # Replace with your target host/group from inventory
  
  vars:
    # Define your project variables
    project_dir: "/home/ubuntu/neptune-v3-release"  # Directory containing docker-compose.yml
    compose_file: "{{ project_dir }}/docker-compose.linux.yml"
    service_name: "neptune-api"  # Main service name from your docker-compose.yml

  tasks:

    - name: Build Docker image using docker-compose
      command: 
        cmd: "docker-compose -f {{ compose_file }} build {{ service_name }}"
        chdir: "{{ project_dir }}"
      register: build_result
      changed_when: build_result.rc == 0

    - name: Debug build output
      debug:
        msg: "{{ build_result.stdout_lines }}"
      when: build_result.stdout is defined
